import "./style.css";
import appLogo from "./assets/nfcx-logo.png";
import { applyTranslations, language, setLanguage, t } from "./i18n";
import {
  AddKey, CancelTask, ConnectDevice, DeleteKey, DisconnectDevice,
  EditBlockASCII, EditBlockHex, ExportKeyDictionary, GetDashboard, GetDiagnostics,
  ClearWorkbench, GetEditableBlock, GetKeyCatalog, GetWorkbench, ImportKeyDictionary, LoadDump,
  PreflightUIDWrite, PreflightWrite, RefreshDevices, SaveDump,
  StartKeyRecovery, StartReadCard, StartUIDWrite, StartWrite, UndoWorkbench,
} from "../wailsjs/go/app/Bindings";
import { EventsOn } from "../wailsjs/runtime/runtime";

type ConnectionStatus = "disconnected" | "connecting" | "ready" | "polling" | "busy" | "recovering" | "error";
interface Device { id: string; name: string; connString: string; transport: string; available: boolean; nested: boolean; darkside: boolean; hardnested: boolean; }
interface Connection { status: ConnectionStatus; label: string; detail: string; errorCode?: string; }
interface Card { present: boolean; uid: string; uidLength: number; atqa: string; sak: string; type: string; typeCode: string; inferred: boolean; }
interface SectorKey { sector: number; keyAStatus: string; keyBStatus: string; keyA?: string; keyB?: string; }
interface KeyEntry { id: string; value: string; sources: string[]; builtin: boolean; removable: boolean; }
interface AccessGroup { group: number; code: string; dataWriteKeys: string; trailerWriteKeys: string; keyBReadable: boolean; }
interface AccessSummary { valid: boolean; error?: string; groups: AccessGroup[]; }
interface Block { block: number; sector: number; kind: "manufacturer" | "data" | "trailer"; hex: string; ascii: string; knownMask: string; status: string; dirty: boolean; warning?: string; access?: AccessSummary; }
interface EditableBlock { block: number; sector: number; kind: "manufacturer" | "data" | "trailer"; hex: string; ascii: string; warning?: string; access?: AccessSummary; }
interface ByteDiff { offset: number; before: string; after: string; wasKnown: boolean; nowKnown: boolean; }
interface BlockDiff { block: number; sector: number; kind: string; bytes: ByteDiff[]; }
interface Workbench { loaded: boolean; saved: boolean; name?: string; layout?: string; complete: boolean; dirty: boolean; dirtyBlocks: number[]; blocks: Block[]; diffs: BlockDiff[]; validation: { valid: boolean; errors: string[]; warnings: string[] }; sourceUid?: string; uidLength: number; }
interface DeviceStateEvent { connection: Connection; device: Device; card: Card; time: string; }
interface CardEvent { type: "appeared" | "removed"; card: Card; time: string; }
interface Task { id: string; name: string; status: string; }
interface RecoveryStep { number: number; stage: string; label: string; status: string; message?: string; }
interface RecoveryResult { outcome: "complete" | "partial" | "failed"; steps: RecoveryStep[]; verifiedKeySlots: number; coveredSectors: number; readableSectors: number; totalSectors: number; dumpComplete: boolean; failedStep?: number; failedStage?: string; reason?: string; hardnestedAvailable: boolean; readerRecovered: boolean; }
interface UIDPreview { currentUid: string; newUid: string; bcc: string; oldBlock0: string; newBlock0: string; }
interface UIDPreflight { token?: string; valid: boolean; preview?: UIDPreview; warning?: string; error?: string; }
interface UIDResult { oldUid: string; newUid?: string; oldBlock0: string; newBlock0: string; actualBlock0?: string; backupPath?: string; verified: boolean; }
interface TaskEvent { taskId: string; kind: string; type: "started" | "progress" | "completed" | "cancelled" | "failed"; phase?: string; progress: number; sector?: number; keyType?: string; attempted?: number; found?: number; block?: number; message: string; time: string; workbench?: Workbench; step?: number; totalSteps?: number; stepStatus?: string; indeterminate?: boolean; recovery?: RecoveryResult; uid?: UIDResult; }
interface Preflight { token?: string; mode: string; valid: boolean; blocks: number[]; trailerBlocks: number[]; skippedBlock0: boolean; warnings: string[]; error?: string; access: Array<{ block: number; sector: number; access: AccessSummary }>; uid?: UIDPreview; }
interface DiagnosticCheck { id: string; name: string; ok: boolean; version?: string; detail?: string; }
interface DiagnosticReport { healthy: boolean; generatedAt: string; build: { version: string; commit: string; buildDate: string; dirty: boolean; goVersion: string; wailsVersion: string; os: string; architecture: string }; libnfc: { available: boolean; version?: string; drivers: string[]; error?: string }; engines: DiagnosticCheck[]; manifest: { found: boolean; verified: boolean; files: number; detail?: string }; currentDevice?: string; supportedReaders: string[]; }
type ThemePreference = "system" | "light" | "dark";

const emptyCard: Card = { present: false, uid: "—", uidLength: 0, atqa: "—", sak: "—", type: "", typeCode: "unknown", inferred: false };
const emptyWorkbench: Workbench = { loaded: false, saved: false, complete: false, dirty: false, dirtyBlocks: [], blocks: [], diffs: [], validation: { valid: false, errors: ["尚未加载 dump"], warnings: [] }, uidLength: 0 };
const root = document.querySelector<HTMLDivElement>("#app");
if (!root) throw new Error("NFCX application root was not found");

root.innerHTML = `
  <div class="app-shell">
    <header class="topbar">
      <div class="brand"><img class="brand-mark" src="${appLogo}" alt="" aria-hidden="true" /><div><h1>NFCX</h1></div></div>
      <div class="top-actions"><button class="ghost-button language-button" id="language-button" type="button"></button><button class="ghost-button theme-button" id="theme-button" type="button"></button><button class="ghost-button" id="about-button" data-i18n="about.title"></button><button class="ghost-button" id="key-manager-button" data-i18n="keys.title"></button></div>
    </header>
    <main class="workspace">
      <aside class="sidebar">
        <section class="panel device-panel">
          <div class="panel-heading"><h2 data-i18n="reader.connection"></h2><button class="icon-button" id="refresh-button" data-i18n-title="reader.refresh" title="">↻</button></div>
          <label class="field-label" for="device-select" data-i18n="reader.available"></label><select id="device-select"></select>
          <div class="device-detail" id="device-detail"></div>
          <button class="primary-button full-button" id="connection-button" data-action="connect" data-i18n="reader.connect"></button>
          <div class="status-card" id="connection-status"><span class="status-light"></span><div><strong data-i18n="reader.loading"></strong><small data-i18n="reader.waiting"></small></div></div>
        </section>
        <section class="panel card-panel">
          <div class="panel-heading compact"><h2 data-i18n="card.summary"></h2><span class="live-badge" id="card-presence" data-i18n="card.absent"></span></div>
          <div class="card-visual" id="card-visual"><div class="card-waves"><i></i><i></i><i></i></div><span>ISO 14443A</span></div><dl class="fact-list" id="card-facts"></dl><button class="danger-button full-button" id="uid-write-button" disabled data-i18n="card.change_uid"></button>
        </section>
        <section class="panel key-status-panel">
          <div class="panel-heading compact"><h2 data-i18n="key_status.title"></h2><span class="counter" id="key-counter">0 / 0</span></div>
          <div class="sector-key-grid" id="sector-key-grid"><div class="empty-small" data-i18n="key_status.empty"></div></div>
        </section>
      </aside>
      <section class="main-column">
        <section class="panel workbench-panel">
          <div class="workbench-toolbar">
            <div><div class="title-line"><h2 data-i18n="workbench.title"></h2><span class="dirty-badge" id="dirty-badge" data-i18n="workbench.not_loaded"></span></div></div>
          <div class="toolbar-actions"><button class="ghost-button" id="load-button" data-i18n="common.load"></button><button class="ghost-button" id="save-button" disabled data-i18n="common.save"></button><button class="ghost-button" id="undo-button" disabled data-i18n="common.undo"></button><button class="ghost-button" id="clear-button" disabled data-i18n="common.clear"></button></div>
          </div>
          <div class="workbench-meta" id="workbench-meta"><span data-i18n="workbench.no_dump"></span></div>
          <div class="table-wrap" id="table-wrap"><div class="empty-workbench"><strong data-i18n="workbench.empty_title"></strong><span data-i18n="workbench.empty_description"></span></div></div>
        </section>
        <section class="panel activity-panel">
          <div class="activity-head"><h2 data-i18n="task.title"></h2><div class="task-actions"><button class="ghost-button compact-button" id="raw-log-button" data-i18n="task.raw_log"></button><span class="task-state" id="task-state" data-i18n="task.idle"></span><button class="danger-button" id="cancel-button" disabled data-i18n="task.cancel"></button></div></div>
          <div class="progress-track"><span id="progress-bar"></span></div>
          <ol class="recovery-steps" id="recovery-steps" hidden><li data-step="1"><b>1</b><span data-i18n="recovery.common_keys"></span></li><li data-step="2"><b>2</b><span>Darkside</span></li><li data-step="3"><b>3</b><span>Nested</span></li><li data-step="4"><b>4</b><span>Hardnested</span></li><li data-step="5"><b>5</b><span data-i18n="recovery.readiness"></span></li></ol>
          <ol class="log-list" id="event-log" aria-live="polite"><li><time>--:--:--</time><span data-i18n="task.waiting"></span></li></ol>
        </section>
        <section class="action-strip"><div><span class="workflow-sequence" data-i18n="workflow.sequence"></span><strong id="operation-hint" data-i18n="workflow.connect_card"></strong></div><div class="action-buttons"><button class="primary-button" id="recover-button" disabled data-i18n="workflow.recover"></button><button class="secondary-button" id="read-button" disabled data-i18n="card.read"></button><button class="danger-button" id="write-changes-button" disabled data-i18n="card.write_changes"></button><button class="danger-button subtle-danger" id="restore-button" disabled data-i18n="card.restore"></button></div></section>
      </section>
    </main>
  </div>
  <dialog class="modal" id="editor-modal"><form method="dialog" class="modal-card editor-card">
    <header><h2 id="editor-title" data-i18n="editor.title"></h2><button class="close-button" value="cancel">×</button></header>
    <div class="warning-box" id="editor-warning" hidden></div><label class="field-label" for="hex-editor" data-i18n="editor.hex"></label><textarea id="hex-editor" rows="3" spellcheck="false"></textarea><label class="field-label" for="ascii-editor" data-i18n="editor.ascii"></label><input id="ascii-editor" maxlength="16" spellcheck="false" /><div class="access-panel" id="access-panel" hidden></div>
    <footer><button class="ghost-button" value="cancel" data-i18n="common.cancel"></button><button class="primary-button" id="apply-hex-button" type="button" data-i18n="editor.apply_hex"></button><button class="secondary-button" id="apply-ascii-button" type="button" data-i18n="editor.apply_ascii"></button></footer>
  </form></dialog>
  <dialog class="modal" id="keys-modal"><form method="dialog" class="modal-card keys-card">
    <header><h2 data-i18n="keys.title"></h2><button class="close-button" value="cancel">×</button></header>
    <div class="key-add-row"><input id="key-input" type="text" maxlength="23" autocomplete="off" data-i18n-placeholder="keys.placeholder" /><button class="primary-button" id="add-key-button" value="default" data-i18n="common.add"></button></div><p class="privacy-note" data-i18n="keys.privacy"></p><div class="import-report" id="import-report" role="status" aria-live="polite" hidden></div><div class="catalog-list" id="catalog-list"></div>
    <footer><button class="ghost-button" id="import-keys-button" value="default" data-i18n="keys.import"></button><button class="ghost-button" id="export-keys-button" value="default" data-i18n="keys.export"></button><button class="secondary-button" value="cancel" data-i18n="common.done"></button></footer>
  </form></dialog>
  <dialog class="modal" id="preflight-modal"><form method="dialog" class="modal-card preflight-card">
    <header><h2 data-i18n="write.preflight_title"></h2><button class="close-button" value="cancel">×</button></header><div id="preflight-content"></div><label class="confirm-row" id="trailer-confirm-row" hidden><input type="checkbox" id="trailer-confirm" /><span data-i18n="write.trailer_confirm"></span></label><div class="danger-confirm" id="restore-uid-confirm-row" hidden><label class="field-label" for="restore-uid-confirm" data-i18n="write.confirm_uid"></label><input id="restore-uid-confirm" autocomplete="off" placeholder="e.g. 12 34 56 78" /></div><footer><button class="ghost-button" value="cancel" data-i18n="common.cancel"></button><button class="danger-button" id="execute-write-button" type="button" data-i18n="write.execute"></button></footer>
  </form></dialog>
  <dialog class="modal compact-modal" id="restore-options-modal"><form method="dialog" class="modal-card"><header><h2 data-i18n="card.restore"></h2><button class="close-button" value="cancel">×</button></header><div class="warning-box" data-i18n="restore.warning"></div><label class="option-row"><input type="checkbox" id="restore-write-uid" /><span data-i18n="restore.write_uid"></span></label><div id="restore-uid-field" hidden><label class="field-label" for="restore-uid-input" data-i18n="restore.uid"></label><input id="restore-uid-input" autocomplete="off" placeholder="e.g. 12 34 56 78" /><small data-i18n="restore.uid_help"></small></div><footer><button class="ghost-button" value="cancel" data-i18n="common.cancel"></button><button class="danger-button" id="restore-preflight-button" type="button" data-i18n="restore.preflight"></button></footer></form></dialog>
  <dialog class="modal compact-modal" id="uid-write-modal"><form method="dialog" class="modal-card"><header><h2 data-i18n="card.change_uid"></h2><button class="close-button" value="cancel">×</button></header><div class="warning-box" data-i18n="uid.warning"></div><label class="field-label" for="uid-write-input" data-i18n="uid.new"></label><input id="uid-write-input" autocomplete="off" placeholder="e.g. 12 34 56 78" /><div id="uid-write-preview"></div><div class="danger-confirm" id="uid-write-confirm-row" hidden><label class="field-label" for="uid-write-confirm" data-i18n="write.confirm_uid"></label><input id="uid-write-confirm" autocomplete="off" placeholder="Enter the same UID again" /></div><footer><button class="ghost-button" value="cancel" data-i18n="common.cancel"></button><button class="secondary-button" id="uid-preflight-button" type="button" data-i18n="common.check"></button><button class="danger-button" id="uid-execute-button" type="button" hidden data-i18n="write.execute"></button></footer></form></dialog>
  <dialog class="modal" id="recovery-confirm-modal"><form method="dialog" class="modal-card"><header><h2 data-i18n="recovery.confirm_title"></h2><button class="close-button" value="cancel">×</button></header><div class="warning-box" data-i18n="recovery.warning"></div><footer><button class="ghost-button" value="cancel" data-i18n="common.cancel"></button><button class="primary-button" id="confirm-recovery-button" type="button" data-i18n="recovery.authorize"></button></footer></form></dialog>
  <dialog class="modal" id="recovery-result-modal"><form method="dialog" class="modal-card"><header><h2 id="recovery-result-title" data-i18n="recovery.result"></h2><button class="close-button" value="cancel">×</button></header><div id="recovery-result-content"></div><footer><button class="primary-button" value="cancel" data-i18n="common.done"></button></footer></form></dialog>
  <dialog class="modal" id="raw-log-modal"><form method="dialog" class="modal-card raw-log-card"><header><h2 data-i18n="task.raw_log"></h2><button class="close-button" value="cancel">×</button></header><pre id="raw-log-content" data-i18n="raw_log.empty"></pre><footer><button class="secondary-button" value="cancel" data-i18n="common.close"></button></footer></form></dialog>
  <dialog class="modal" id="diagnostics-modal"><form method="dialog" class="modal-card diagnostics-card"><header><h2 data-i18n="diagnostics.title"></h2><button class="close-button" value="cancel">×</button></header><div id="diagnostics-content"><div class="empty-small" data-i18n="diagnostics.loading"></div></div><footer><button class="ghost-button" id="diagnostics-refresh" type="button" data-i18n="diagnostics.refresh"></button><button class="secondary-button" value="cancel" data-i18n="common.close"></button></footer></form></dialog>
  <dialog class="modal compact-modal" id="about-modal"><form method="dialog" class="modal-card"><header><h2 data-i18n="about.title"></h2><button class="close-button" value="cancel">×</button></header><div class="about-content"><p><strong>NFCX</strong> <span id="about-version"></span></p><p><span data-i18n="about.author"></span>: BennyThink · local hardening: zhm20</p><p class="privacy-note" data-i18n="about.local_only"></p><footer><button class="ghost-button" id="diagnostics-button" type="button" data-i18n="about.diagnostics"></button><button class="secondary-button" value="cancel" data-i18n="common.close"></button></footer></div></form></dialog>`;

function el<T extends HTMLElement>(selector: string): T { const value = document.querySelector<T>(selector); if (!value) throw new Error(`Missing UI element ${selector}`); return value; }
function text(tag: string, value: string, className?: string): HTMLElement { const node = document.createElement(tag); node.textContent = value; if (className) node.className = className; return node; }
function spacedHex(value: string): string { return value.match(/.{1,2}/g)?.join(" ") ?? value; }
function sourceLabel(value: string): string { return ({ builtin: t("keys.source_builtin"), user_input: t("keys.source_user_input"), file_import: t("keys.source_file_import"), read_context: t("keys.source_read_context"), attack_engine: t("keys.source_attack_engine") } as Record<string, string>)[value] ?? value; }
const deviceSelect = el<HTMLSelectElement>("#device-select"), connectionButton = el<HTMLButtonElement>("#connection-button"), refreshButton = el<HTMLButtonElement>("#refresh-button");
const deviceDetail = el<HTMLDivElement>("#device-detail"), connectionStatus = el<HTMLDivElement>("#connection-status"), cardFacts = el<HTMLDListElement>("#card-facts"), sectorGrid = el<HTMLDivElement>("#sector-key-grid"), tableWrap = el<HTMLDivElement>("#table-wrap"), workbenchMeta = el<HTMLDivElement>("#workbench-meta"), eventLog = el<HTMLOListElement>("#event-log"), recoverySteps = el<HTMLOListElement>("#recovery-steps");
const cardPresence = el<HTMLSpanElement>("#card-presence"), cardVisual = el<HTMLDivElement>("#card-visual"), keyCounter = el<HTMLSpanElement>("#key-counter"), dirtyBadge = el<HTMLSpanElement>("#dirty-badge"), taskState = el<HTMLSpanElement>("#task-state"), progressBar = el<HTMLSpanElement>("#progress-bar");
const loadButton = el<HTMLButtonElement>("#load-button"), saveButton = el<HTMLButtonElement>("#save-button"), undoButton = el<HTMLButtonElement>("#undo-button"), clearButton = el<HTMLButtonElement>("#clear-button"), recoverButton = el<HTMLButtonElement>("#recover-button"), readButton = el<HTMLButtonElement>("#read-button"), writeChangesButton = el<HTMLButtonElement>("#write-changes-button"), restoreButton = el<HTMLButtonElement>("#restore-button"), uidWriteButton = el<HTMLButtonElement>("#uid-write-button"), cancelButton = el<HTMLButtonElement>("#cancel-button"), executeWriteButton = el<HTMLButtonElement>("#execute-write-button"), rawLogButton = el<HTMLButtonElement>("#raw-log-button");
const operationHint = el<HTMLElement>("#operation-hint"), themeButton = el<HTMLButtonElement>("#theme-button"), editorModal = el<HTMLDialogElement>("#editor-modal"), editorTitle = el<HTMLHeadingElement>("#editor-title"), editorWarning = el<HTMLDivElement>("#editor-warning"), hexEditor = el<HTMLTextAreaElement>("#hex-editor"), asciiEditor = el<HTMLInputElement>("#ascii-editor"), accessPanel = el<HTMLDivElement>("#access-panel"), keysModal = el<HTMLDialogElement>("#keys-modal"), keyInput = el<HTMLInputElement>("#key-input"), importReport = el<HTMLDivElement>("#import-report"), catalogList = el<HTMLDivElement>("#catalog-list"), preflightModal = el<HTMLDialogElement>("#preflight-modal"), preflightContent = el<HTMLDivElement>("#preflight-content"), trailerConfirmRow = el<HTMLElement>("#trailer-confirm-row"), trailerConfirm = el<HTMLInputElement>("#trailer-confirm"), restoreUIDConfirmRow = el<HTMLElement>("#restore-uid-confirm-row"), restoreUIDConfirm = el<HTMLInputElement>("#restore-uid-confirm"), restoreOptionsModal = el<HTMLDialogElement>("#restore-options-modal"), restoreWriteUID = el<HTMLInputElement>("#restore-write-uid"), restoreUIDField = el<HTMLElement>("#restore-uid-field"), restoreUIDInput = el<HTMLInputElement>("#restore-uid-input"), uidWriteModal = el<HTMLDialogElement>("#uid-write-modal"), uidWriteInput = el<HTMLInputElement>("#uid-write-input"), uidWritePreview = el<HTMLElement>("#uid-write-preview"), uidWriteConfirmRow = el<HTMLElement>("#uid-write-confirm-row"), uidWriteConfirm = el<HTMLInputElement>("#uid-write-confirm"), uidPreflightButton = el<HTMLButtonElement>("#uid-preflight-button"), uidExecuteButton = el<HTMLButtonElement>("#uid-execute-button"), recoveryConfirmModal = el<HTMLDialogElement>("#recovery-confirm-modal"), confirmRecoveryButton = el<HTMLButtonElement>("#confirm-recovery-button"), recoveryResultModal = el<HTMLDialogElement>("#recovery-result-modal"), recoveryResultTitle = el<HTMLHeadingElement>("#recovery-result-title"), recoveryResultContent = el<HTMLDivElement>("#recovery-result-content"), rawLogModal = el<HTMLDialogElement>("#raw-log-modal"), rawLogContent = el<HTMLPreElement>("#raw-log-content");
const diagnosticsModal = el<HTMLDialogElement>("#diagnostics-modal"), diagnosticsContent = el<HTMLDivElement>("#diagnostics-content"), diagnosticsButton = el<HTMLButtonElement>("#diagnostics-button"), diagnosticsRefresh = el<HTMLButtonElement>("#diagnostics-refresh"), aboutModal = el<HTMLDialogElement>("#about-modal"), aboutButton = el<HTMLButtonElement>("#about-button"), aboutVersion = el<HTMLElement>("#about-version");
const languageButton = el<HTMLButtonElement>("#language-button");

let devices: Device[] = [], connection: Connection = { status: "disconnected", label: "", detail: "" }, card: Card = emptyCard, sectorKeys: SectorKey[] = [], catalog: KeyEntry[] = [], bench: Workbench = emptyWorkbench, activeTask: Task | null = null, startingTask = false, cardPrepared = false, editingBlock = -1, pendingPreflight: Preflight | null = null, pendingUIDPreflight: UIDPreflight | null = null, pendingRecoveryResult: RecoveryResult | null = null, rawStreams = { stdout: "", stderr: "" };
const terminalTaskIDs = new Set<string>();
const themeStorageKey = "nfcx-theme";
let themePreference: ThemePreference = "system";

function storedTheme(): ThemePreference { try { const stored = window.localStorage.getItem(themeStorageKey); return stored === "light" || stored === "dark" ? stored : "system"; } catch { return "system"; } }
function applyTheme(theme: ThemePreference): void { themePreference = theme; if (theme === "system") document.documentElement.removeAttribute("data-theme"); else document.documentElement.dataset.theme = theme; const labels: Record<ThemePreference, string> = { system: t("theme.system"), light: t("theme.light"), dark: t("theme.dark") }; themeButton.textContent = labels[theme]; themeButton.title = labels[theme]; try { window.localStorage.setItem(themeStorageKey, theme); } catch { /* theme still applies for the current session */ } }

function refreshLanguage(): void {
  applyTranslations();
  languageButton.textContent = `◎ ${t(language() === "en" ? "language.en" : "language.zh_cn")}`;
  languageButton.title = t("language.switch");
  applyTheme(themePreference);
  renderDevices(devices, deviceSelect.value);
  renderConnection(connection);
  renderCard(card);
  renderSectorKeys(sectorKeys);
  renderWorkbench(bench);
  if (keysModal.open) renderCatalog(catalog);
}

function appendLog(message: string, timestamp = new Date().toISOString(), tone = ""): void { if (eventLog.children.length === 1 && eventLog.querySelector("[data-i18n='task.waiting']")) eventLog.replaceChildren(); const item = document.createElement("li"); if (tone) item.dataset.tone = tone; const parsed = new Date(timestamp); item.append(text("time", Number.isNaN(parsed.valueOf()) ? "--:--:--" : parsed.toLocaleTimeString(language(), { hour12: false })), text("span", message)); eventLog.prepend(item); while (eventLog.children.length > 9) eventLog.lastElementChild?.remove(); }
function appendRawLog(engine: string, stream: string, chunk: string, _timestamp: string): void { const channel = stream === "stderr" ? "stderr" : "stdout"; rawStreams[channel] += `[${engine || "external"}] ${chunk}`; rawLogContent.textContent = `STDOUT\n${rawStreams.stdout}\n\nSTDERR\n${rawStreams.stderr}`; }
function phaseLabel(phase?: string): string { return ({ queued: "已排队", preflight: "确认目标卡", releasing_device: "释放设备", starting: "正在启动", running: "运行中", cancelling: "正在取消", validating_result: "校验输出", reopening_device: "恢复设备", verifying_keys: "复验候选密钥", merging_result: "合并结果", mfcuk_stage: "阶段 1/2 · MFCUK", verifying_seed: "验证 MFCUK 候选", mfoc_stage: "阶段 2/2 · MFOC", reading_dump: "读取卡片", common_keys: "1/5 · 常见密钥", darkside: "2/5 · Darkside", nested: "3/5 · Nested", hardnested: "4/5 · Hardnested", readiness: "5/5 · 读取验证", succeeded: "外部步骤完成", failed: "失败", cancelled: "已取消" } as Record<string, string>)[phase ?? ""] ?? phase ?? "运行中"; }
function resetRecoverySteps(): void { recoverySteps.hidden = false; recoverySteps.querySelectorAll<HTMLElement>("li").forEach((item) => { item.dataset.status = "pending"; item.removeAttribute("title"); }); pendingRecoveryResult = null; }
function updateRecoveryStep(event: TaskEvent): void { if (!event.step) return; recoverySteps.hidden = false; const item = recoverySteps.querySelector<HTMLElement>(`[data-step="${event.step}"]`); if (!item) return; item.dataset.status = event.stepStatus || "running"; if (event.message) item.title = event.message; }
function recoveryStatusLabel(status: string): string { return ({ pending: "等待", running: "运行中", completed: "完成", skipped: "跳过", failed: "失败", unavailable: "不可用" } as Record<string, string>)[status] ?? status; }
function renderRecoveryResult(result: RecoveryResult): void { const complete = result.outcome === "complete", partial = result.outcome === "partial"; recoveryResultModal.dataset.outcome = result.outcome; recoveryResultTitle.textContent = complete ? "卡片密钥恢复完成" : partial ? "已保留部分恢复结果" : "卡片密钥恢复失败"; const summary = document.createElement("div"); summary.className = `recovery-result-summary ${result.outcome}`; summary.append(text("strong", complete ? `全部 ${result.totalSectors} 个扇区均可读取` : `读取验证 ${result.readableSectors} / ${result.totalSectors} 个扇区`), text("span", `已验证密钥槽位 ${result.verifiedKeySlots} · 密钥覆盖扇区 ${result.coveredSectors} · 读卡器${result.readerRecovered ? "已恢复" : "恢复状态异常"}`)); if (result.reason) summary.append(text("p", `${result.failedStep ? `第 ${result.failedStep}/5 步：` : ""}${result.reason}`)); const list = document.createElement("ol"); list.className = "recovery-result-steps"; result.steps.forEach((step) => { const item = document.createElement("li"); item.dataset.status = step.status; item.append(text("b", String(step.number)), text("strong", step.label), text("span", recoveryStatusLabel(step.status)), text("small", step.message || "")); list.append(item); }); recoveryResultContent.replaceChildren(summary, list); }
function renderDevices(next: Device[], selected = deviceSelect.value): void { devices = [...next]; deviceSelect.replaceChildren(); if (!devices.length) { const option = document.createElement("option"); option.value = ""; option.textContent = t("reader.no_devices"); deviceSelect.append(option); } else devices.forEach((device) => { const option = document.createElement("option"); option.value = device.id; option.textContent = device.name; option.disabled = !device.available; option.selected = device.id === selected; deviceSelect.append(option); }); renderDeviceDetail(); updateActions(); }
function renderDeviceDetail(): void { const selected = devices.find((item) => item.id === deviceSelect.value); deviceDetail.replaceChildren(); if (!selected) { deviceDetail.append(text("span", t("reader.refresh_hint"))); return; } deviceDetail.append(text("span", `${selected.transport} · ${selected.nested ? "Nested" : "Nested disabled"} · ${selected.darkside ? "Darkside" : "Darkside disabled"} · ${selected.hardnested ? "Hardnested" : "Hardnested disabled"}`)); }
function renderConnection(next: Connection): void { connection = next; connectionStatus.dataset.status = next.status; const detail = next.detail || (next.errorCode ? `Error: ${next.errorCode}` : t("reader.waiting_action")); const statusLabels: Partial<Record<ConnectionStatus, string>> = { disconnected: t("reader.disconnected"), connecting: t("reader.connecting"), polling: t("reader.detecting_card") }; const label = (statusLabels[next.status] ?? next.label) || t("status.unknown"); const content = document.createElement("div"); content.append(text("strong", label), text("small", detail)); connectionStatus.replaceChildren(text("span", "", "status-light"), content); const connected = ["ready", "polling", "busy", "recovering"].includes(next.status); connectionButton.dataset.action = connected ? "disconnect" : "connect"; connectionButton.textContent = connected ? (next.status === "recovering" ? t("reader.recover_disconnect") : t("reader.disconnect")) : (next.status === "connecting" ? t("reader.connecting") : t("reader.connect")); connectionButton.className = connected ? "secondary-button full-button" : "primary-button full-button"; connectionButton.disabled = next.status === "connecting" || !!activeTask; updateActions(); }
function renderCard(next: Card): void { card = next; if (!next.present) { cardPrepared = false; if (recoveryConfirmModal.open) recoveryConfirmModal.close(); } cardFacts.replaceChildren(); const cardType = !next.typeCode || next.typeCode === "unknown" || !next.inferred ? t("status.unknown") : next.type; [["UID", next.uid], [t("card.uid_length"), next.present ? t("card.bytes", { count: next.uidLength }) : "—"], ["ATQA", next.atqa], ["SAK", next.sak], [t("card.type"), cardType]].forEach(([label, value]) => cardFacts.append(text("dt", label), text("dd", value))); cardPresence.textContent = next.present ? t("card.present") : t("card.absent"); cardPresence.dataset.present = String(next.present); cardVisual.dataset.present = String(next.present); updateActions(); }
function renderSectorKeys(next: SectorKey[]): void { sectorKeys = next ?? []; sectorGrid.replaceChildren(); let found = 0; if (!sectorKeys.length) sectorGrid.append(text("div", t("key_status.empty"), "empty-small")); else sectorKeys.forEach((entry) => { const row = document.createElement("div"); row.className = "sector-key-row"; const a = text("span", entry.keyAStatus === "verified" ? `A · ${entry.keyA}` : `A · ${t("key_status.unknown")}`, `key-chip ${entry.keyAStatus}`), b = text("span", entry.keyBStatus === "verified" ? `B · ${entry.keyB}` : `B · ${t("key_status.unknown")}`, `key-chip ${entry.keyBStatus}`); if (entry.keyAStatus === "verified") found++; if (entry.keyBStatus === "verified") found++; row.append(text("strong", `S${entry.sector.toString().padStart(2, "0")}`), a, b); sectorGrid.append(row); }); keyCounter.textContent = `${found} / ${sectorKeys.length * 2}`; updateActions(); }
function renderAccess(summary?: AccessSummary): HTMLElement { const container = document.createElement("div"); if (!summary?.valid) { container.append(text("p", summary?.error || "访问控制位无效", "validation-error")); return container; } const table = document.createElement("table"); table.className = "access-table"; table.innerHTML = "<thead><tr><th>组</th><th>C1C2C3</th><th>数据写入</th><th>控制块写入</th><th>密钥 B</th></tr></thead>"; const body = document.createElement("tbody"); summary.groups.forEach((group) => { const row = document.createElement("tr"); [String(group.group), group.code, group.dataWriteKeys, group.trailerWriteKeys, group.keyBReadable ? "可作数据读取" : "仅作认证密钥"].forEach((value) => row.append(text("td", value))); body.append(row); }); table.append(body); container.append(table); return container; }

function renderWorkbench(next: Workbench): void {
  bench = next ?? emptyWorkbench; tableWrap.replaceChildren(); dirtyBadge.textContent = !bench.loaded ? t("workbench.not_loaded") : bench.dirty ? t("workbench.dirty_blocks", { count: bench.dirtyBlocks.length }) : bench.saved ? t("workbench.saved") : t("workbench.unsaved"); dirtyBadge.dataset.dirty = String(bench.dirty); dirtyBadge.dataset.saved = String(bench.saved); workbenchMeta.replaceChildren();
  if (!bench.loaded) { workbenchMeta.append(text("span", t("workbench.no_dump"))); const empty = document.createElement("div"); empty.className = "empty-workbench"; empty.append(text("strong", t("workbench.empty_title")), text("span", t("workbench.empty_description"))); tableWrap.append(empty); }
  else { workbenchMeta.append(text("span", bench.name || t("workbench.card_read")), text("span", bench.layout === "classic_4k" ? "MIFARE Classic 4K" : "MIFARE Classic 1K"), text("span", bench.complete ? t("workbench.complete") : t("workbench.incomplete"), bench.complete ? "meta-ok" : "meta-warn")); const table = document.createElement("table"); table.className = "memory-table"; table.innerHTML = `<thead><tr><th>${t("workbench.sector")}</th><th>${t("workbench.block")}</th><th>${t("workbench.type")}</th><th>${t("editor.hex")}</th><th>ASCII</th><th>${t("workbench.status")}</th></tr></thead>`; const body = document.createElement("tbody"); bench.blocks.forEach((block) => { const row = document.createElement("tr"); row.className = `${block.kind}-row${block.dirty ? " dirty-row" : ""}`; row.tabIndex = 0; const kindLabel = block.kind === "manufacturer" ? t("workbench.manufacturer") : block.kind === "trailer" ? t("workbench.trailer") : t("workbench.data"); row.append(text("td", String(block.sector)), text("td", block.block.toString().padStart(3, "0"), "block-number"), text("td", kindLabel, `kind-label ${block.kind}`), text("td", spacedHex(block.hex), "hex-data"), text("td", block.ascii, "ascii-data"), text("td", block.dirty ? t("workbench.modified") : block.status, block.dirty ? "dirty-text" : "status-text")); row.addEventListener("dblclick", () => openEditor(block)); row.addEventListener("keydown", (event) => { if (event.key === "Enter") openEditor(block); }); body.append(row); }); table.append(body); tableWrap.append(table); }
  updateActions();
}

function renderCatalog(next: KeyEntry[]): void { catalog = next ?? []; catalogList.replaceChildren(); catalog.forEach((entry) => { const row = document.createElement("div"); row.className = "catalog-row"; const details = document.createElement("div"); details.append(text("code", entry.value), text("small", entry.sources.map(sourceLabel).join(" · "))); const remove = document.createElement("button"); remove.type = "button"; remove.className = "text-danger"; remove.textContent = entry.removable ? t("common.delete") : t("keys.source_builtin"); remove.disabled = !entry.removable; remove.addEventListener("click", async () => { try { renderCatalog((await DeleteKey(entry.id)) as KeyEntry[]); appendLog("已移除用户密钥"); } catch (error) { appendLog(`删除失败：${String(error)}`, undefined, "error"); } }); row.append(details, remove); catalogList.append(row); }); }
function diagnosticRow(label: string, value: string, ok?: boolean): HTMLElement { const row = document.createElement("div"); row.className = "diagnostic-row"; if (ok !== undefined) row.dataset.ok = String(ok); row.append(text("strong", label), text("span", value)); return row; }
function renderDiagnostics(report: DiagnosticReport): void { diagnosticsContent.replaceChildren(); const summary = document.createElement("div"); summary.className = "diagnostic-summary"; summary.dataset.ok = String(report.healthy); summary.append(text("strong", report.healthy ? t("diagnostics.healthy") : t("diagnostics.unhealthy")), text("span", `${report.build.os}/${report.build.architecture} · ${report.generatedAt}`)); const build = document.createElement("section"); build.className = "diagnostic-section"; build.append(text("h3", t("diagnostics.build")), diagnosticRow("NFCX", `${report.build.version}${report.build.dirty ? " (dirty)" : ""}`), diagnosticRow("Commit", report.build.commit), diagnosticRow("Go / Wails", `${report.build.goVersion} / ${report.build.wailsVersion}`), diagnosticRow(t("diagnostics.build_time"), report.build.buildDate)); const native = document.createElement("section"); native.className = "diagnostic-section"; native.append(text("h3", t("diagnostics.nfc_runtime")), diagnosticRow("libnfc", report.libnfc.version || report.libnfc.error || t("status.unavailable"), report.libnfc.available), diagnosticRow(t("diagnostics.enabled_drivers"), report.libnfc.drivers.join(", ") || t("diagnostics.none")), diagnosticRow(t("diagnostics.support_statement"), report.supportedReaders.join("；"))); if (report.currentDevice) native.append(diagnosticRow(t("diagnostics.current_device"), report.currentDevice)); const engines = document.createElement("section"); engines.className = "diagnostic-section"; engines.append(text("h3", t("diagnostics.external_engines"))); report.engines.forEach((item) => engines.append(diagnosticRow(item.name, item.ok ? `${item.version || t("diagnostics.available")}` : item.detail || t("status.unavailable"), item.ok))); const manifest = document.createElement("section"); manifest.className = "diagnostic-section"; manifest.append(text("h3", t("diagnostics.integrity")), diagnosticRow("Runtime manifest", report.manifest.verified ? t("diagnostics.files_verified", { count: report.manifest.files }) : report.manifest.detail || t("diagnostics.failed"), report.manifest.verified)); diagnosticsContent.append(summary, build, native, engines, manifest); }
async function loadDiagnostics(): Promise<void> { diagnosticsRefresh.disabled = true; diagnosticsContent.replaceChildren(text("div", t("diagnostics.checking"), "empty-small")); try { renderDiagnostics((await GetDiagnostics()) as DiagnosticReport); } catch (error) { diagnosticsContent.replaceChildren(text("div", t("diagnostics.failed_with_error", { error: String(error) }), "preflight-error")); } finally { diagnosticsRefresh.disabled = false; } }
function clearCatalogReport(): void { importReport.hidden = true; importReport.removeAttribute("data-tone"); importReport.setAttribute("role", "status"); importReport.replaceChildren(); }
function showCatalogReport(message: string, tone: "info" | "error" = "info"): void { importReport.dataset.tone = tone; importReport.setAttribute("role", tone === "error" ? "alert" : "status"); importReport.replaceChildren(text("strong", message)); importReport.hidden = false; }
function updateActions(): void {
  const classic = card.present && ["mifare_classic_1k", "mifare_classic_4k"].includes(card.typeCode);
  const busy = startingTask || !!activeTask || connection.status === "busy" || connection.status === "connecting" || connection.status === "recovering";
  const selectedDevice = devices.find((item) => item.id === deviceSelect.value && item.available);
  const readerReady = connection.status === "ready" || connection.status === "polling";
  const prepared = classic && cardPrepared;
  const verified = sectorKeys.reduce((count, entry) => count + Number(entry.keyAStatus === "verified") + Number(entry.keyBStatus === "verified"), 0);
  const sector0Ready = !!sectorKeys[0] && (sectorKeys[0].keyAStatus === "verified" || sectorKeys[0].keyBStatus === "verified");
  refreshButton.disabled = busy;
  connectionButton.disabled = connection.status === "connecting" || startingTask || !!activeTask || (connectionButton.dataset.action === "connect" && !selectedDevice);
  recoverButton.disabled = !classic || !readerReady || busy;
  confirmRecoveryButton.disabled = !classic;
  readButton.disabled = !prepared || busy;
  readButton.textContent = prepared ? t("card.read_all") : t("card.read");
  loadButton.disabled = false;
  saveButton.disabled = !bench.loaded || busy;
  undoButton.disabled = !bench.dirty || busy;
  clearButton.disabled = !bench.loaded || busy;
  writeChangesButton.disabled = !prepared || busy || !bench.loaded || !bench.complete || !bench.dirty;
  restoreButton.disabled = !prepared || busy || !bench.loaded || !bench.complete;
  uidWriteButton.disabled = !prepared || card.typeCode !== "mifare_classic_1k" || card.uidLength !== 4 || !sector0Ready || !readerReady || busy;
  cancelButton.disabled = !activeTask;
  operationHint.textContent = busy ? `正在执行：${activeTask?.name ?? "正在启动任务"}` : !classic ? t("workflow.connect_card") : !cardPrepared ? t("workflow.card_ready") : !bench.loaded ? t("workflow.read_ready", { count: verified }) : bench.dirty ? t("workflow.save_or_write") : bench.saved ? t("workflow.saved") : t("workflow.loaded");
}
function editableASCIIValue(editable: EditableBlock): string { const bytes = editable.hex.match(/.{2}/g)?.map((value) => Number.parseInt(value, 16)) ?? []; const firstZero = bytes.indexOf(0); const content = firstZero < 0 ? bytes : bytes.slice(0, firstZero); const padding = firstZero < 0 ? [] : bytes.slice(firstZero); if (content.every((value) => value >= 0x20 && value <= 0x7e) && padding.every((value) => value === 0)) return String.fromCharCode(...content); return ""; }
async function openEditor(block: Block): Promise<void> { if (activeTask) return; try { const editable = (await GetEditableBlock(block.block)) as EditableBlock; editingBlock = editable.block; editorTitle.textContent = editable.kind === "trailer" ? t("editor.trailer_title", { sector: editable.sector, block: editable.block }) : editable.kind === "manufacturer" ? t("editor.manufacturer_title") : t("editor.data_title", { block: editable.block }); hexEditor.value = spacedHex(editable.hex); asciiEditor.value = editableASCIIValue(editable); editorWarning.hidden = !editable.warning; editorWarning.textContent = editable.warning || ""; accessPanel.hidden = editable.kind !== "trailer"; accessPanel.replaceChildren(); if (editable.kind === "trailer") accessPanel.append(text("h3", "访问控制位说明"), renderAccess(editable.access)); editorModal.showModal(); } catch (error) { appendLog(`无法打开编辑器：${String(error)}`, undefined, "error"); } }
async function startTask(starter: () => Promise<unknown>, clearBeforeStart = false): Promise<void> { startingTask = true; rawStreams = { stdout: "", stderr: "" }; rawLogContent.textContent = "尚无外部进程输出"; taskState.textContent = "正在启动"; taskState.dataset.state = "running"; progressBar.classList.add("indeterminate"); progressBar.style.width = "2%"; if (clearBeforeStart) renderWorkbench(emptyWorkbench); updateActions(); try { const task = (await starter()) as Task; if (terminalTaskIDs.delete(task.id)) { activeTask = null; return; } activeTask = task; taskState.textContent = "运行中"; taskState.dataset.state = "running"; progressBar.style.width = "2%"; } catch (error) { appendLog(`无法启动任务：${String(error)}`, undefined, "error"); activeTask = null; taskState.textContent = "启动失败"; taskState.dataset.state = "failed"; progressBar.classList.remove("indeterminate"); progressBar.style.width = "0%"; if (clearBeforeStart) { try { renderWorkbench((await GetWorkbench()) as Workbench); } catch { /* retain the explicit empty state when refresh also fails */ } } } finally { startingTask = false; updateActions(); } }

function uidPreviewElement(preview: UIDPreview): HTMLElement { const box = document.createElement("div"); box.className = "uid-preview-card"; box.append(text("strong", `${preview.currentUid} → ${preview.newUid}`), text("span", `BCC：${preview.bcc}`), text("code", `原 block 0　${preview.oldBlock0}`), text("code", `新 block 0　${preview.newBlock0}`)); return box; }
async function openPreflight(mode: "changes" | "full", writeUid = false, uid = ""): Promise<void> {
  appendLog("正在执行只读预检…");
  try { pendingPreflight = (await PreflightWrite({ mode, writeUid, uid })) as Preflight; preflightContent.replaceChildren(); trailerConfirmRow.hidden = true; restoreUIDConfirmRow.hidden = true; if (!pendingPreflight.valid) { preflightContent.append(text("div", pendingPreflight.error || "预检未通过", "preflight-error")); executeWriteButton.disabled = true; } else { const summary = document.createElement("div"); summary.className = "preflight-summary"; summary.append(text("strong", `计划写入 ${pendingPreflight.blocks.length} 个 block`), text("span", pendingPreflight.blocks.join(", "))); preflightContent.append(summary); if (mode === "changes" && bench.diffs.length) { const diffList = document.createElement("div"); diffList.className = "diff-list"; diffList.append(text("h3", "工作副本差异")); bench.diffs.forEach((diff) => diffList.append(text("p", `Block ${diff.block}：${diff.bytes.map((item) => `${item.offset.toString().padStart(2, "0")} ${item.before}→${item.after}`).join(" · ")}`))); preflightContent.append(diffList); } if (pendingPreflight.uid) preflightContent.append(uidPreviewElement(pendingPreflight.uid)); pendingPreflight.warnings.forEach((warning) => preflightContent.append(text("div", warning, "warning-line"))); pendingPreflight.access.forEach((item) => { const section = document.createElement("section"); section.className = "trailer-access"; section.append(text("h3", `扇区 ${item.sector} · 控制块 ${item.block}`), renderAccess(item.access)); preflightContent.append(section); }); trailerConfirmRow.hidden = !pendingPreflight.trailerBlocks.length; trailerConfirm.checked = false; restoreUIDConfirmRow.hidden = !pendingPreflight.uid; restoreUIDConfirm.value = ""; executeWriteButton.disabled = false; } preflightModal.showModal(); } catch (error) { appendLog(`预检失败：${String(error)}`, undefined, "error"); }
}

deviceSelect.addEventListener("change", () => { renderDeviceDetail(); updateActions(); });
refreshButton.addEventListener("click", async () => { refreshButton.disabled = true; try { const found = (await RefreshDevices()) as Device[]; renderDevices(found); appendLog(found.length ? `发现 ${found.length} 个读卡器` : "未自动发现读卡器"); } catch (error) { appendLog(`刷新失败：${String(error)}`, undefined, "error"); } finally { refreshButton.disabled = false; } });
connectionButton.addEventListener("click", async () => { connectionButton.disabled = true; try { if (connectionButton.dataset.action === "disconnect") await DisconnectDevice(); else { const selected = devices.find((item) => item.id === deviceSelect.value && item.available); if (!selected) throw new Error("请选择自动发现的读卡器"); await ConnectDevice(selected.connString); } } catch (error) { appendLog(`设备操作失败：${String(error)}`, undefined, "error"); renderConnection(connection); } });
themeButton.addEventListener("click", () => { const sequence: ThemePreference[] = ["system", "light", "dark"]; applyTheme(sequence[(sequence.indexOf(themePreference) + 1) % sequence.length]); });
languageButton.addEventListener("click", () => { setLanguage(language() === "en" ? "zh-CN" : "en"); refreshLanguage(); });
diagnosticsButton.addEventListener("click", () => { diagnosticsModal.showModal(); void loadDiagnostics(); });
diagnosticsRefresh.addEventListener("click", () => void loadDiagnostics());
aboutButton.addEventListener("click", () => aboutModal.showModal());
el<HTMLButtonElement>("#key-manager-button").addEventListener("click", async () => { try { renderCatalog((await GetKeyCatalog()) as KeyEntry[]); clearCatalogReport(); keysModal.showModal(); } catch (error) { appendLog(`密钥库载入失败：${String(error)}`, undefined, "error"); } });
el<HTMLButtonElement>("#add-key-button").addEventListener("click", async (event) => { event.preventDefault(); const value = keyInput.value.replace(/\s/g, ""); if (!/^[\da-fA-F]{12}$/.test(value)) { showCatalogReport(t("keys.invalid_format"), "error"); return; } try { renderCatalog((await AddKey(value)) as KeyEntry[]); keyInput.value = ""; showCatalogReport(t("keys.added")); appendLog(t("keys.added")); } catch (error) { showCatalogReport(t("keys.add_failed", { error: String(error) }), "error"); appendLog(t("keys.add_failed", { error: String(error) }), undefined, "error"); } });
el<HTMLButtonElement>("#import-keys-button").addEventListener("click", async (event) => { event.preventDefault(); try { const report = await ImportKeyDictionary(); if (!report.cancelled) { renderCatalog(report.keys as KeyEntry[]); showCatalogReport(`新增 ${report.added} · 重复 ${report.duplicates} · 非法 ${report.issues.length}`); report.issues.slice(0, 8).forEach((issue) => importReport.append(text("span", `第 ${issue.line} 行：${issue.message}`))); appendLog(`字典导入：新增 ${report.added}，重复 ${report.duplicates}，非法 ${report.issues.length}`); } } catch (error) { showCatalogReport(`导入失败：${String(error)}`, "error"); appendLog(`导入失败：${String(error)}`, undefined, "error"); } });
el<HTMLButtonElement>("#export-keys-button").addEventListener("click", async (event) => { event.preventDefault(); if (!window.confirm(t("security.key_export_warning"))) return; try { const result = await ExportKeyDictionary(); if (!result.cancelled) appendLog(`已导出 ${result.count} 个密钥至 ${result.path}`); } catch (error) { appendLog(`导出失败：${String(error)}`, undefined, "error"); } });
loadButton.addEventListener("click", async () => { let discard = false; if (bench.dirty) { discard = window.confirm("当前工作副本有未保存修改。放弃修改并加载其他文件？"); if (!discard) return; } try { renderWorkbench((await LoadDump(discard)) as Workbench); appendLog("Dump 已载入工作台"); } catch (error) { appendLog(`加载失败：${String(error)}`, undefined, "error"); } });
saveButton.addEventListener("click", async () => { if (!window.confirm(t("security.dump_warning"))) return; try { const result = await SaveDump(); if (!result.cancelled) appendLog(`已保存 ${result.path}${result.sidecar ? ` 与 ${result.sidecar}` : ""}`); } catch (error) { appendLog(`保存失败：${String(error)}`, undefined, "error"); } });
undoButton.addEventListener("click", async () => { try { renderWorkbench((await UndoWorkbench()) as Workbench); } catch (error) { appendLog(`撤销失败：${String(error)}`, undefined, "error"); } });
clearButton.addEventListener("click", async () => { const previous = bench; renderWorkbench(emptyWorkbench); appendLog("正在清空工作区…"); try { renderWorkbench((await ClearWorkbench()) as Workbench); appendLog("工作区已清空", undefined, "success"); } catch (error) { try { renderWorkbench((await GetWorkbench()) as Workbench); } catch { renderWorkbench(previous); } appendLog(`清空失败：${String(error)}`, undefined, "error"); } });
el<HTMLButtonElement>("#apply-hex-button").addEventListener("click", async (event) => { event.preventDefault(); try { renderWorkbench((await EditBlockHex(editingBlock, hexEditor.value)) as Workbench); editorModal.close(); appendLog(`Block ${editingBlock} 已在工作副本中修改`); } catch (error) { appendLog(`Hex 编辑失败：${String(error)}`, undefined, "error"); } });
el<HTMLButtonElement>("#apply-ascii-button").addEventListener("click", async (event) => { event.preventDefault(); try { renderWorkbench((await EditBlockASCII(editingBlock, asciiEditor.value)) as Workbench); editorModal.close(); appendLog(`Block ${editingBlock} 已在工作副本中修改`); } catch (error) { appendLog(`ASCII 编辑失败：${String(error)}`, undefined, "error"); } });
recoverButton.addEventListener("click", () => recoveryConfirmModal.showModal()); confirmRecoveryButton.addEventListener("click", (event) => { event.preventDefault(); if (!card.present) { recoveryConfirmModal.close(); appendLog("卡片已离开，无法开始自动恢复密钥", undefined, "error"); return; } if (startingTask || activeTask) { recoveryConfirmModal.close(); appendLog("已有任务正在运行，请先完成或取消当前任务", undefined, "error"); return; } cardPrepared = false; recoveryConfirmModal.close(); resetRecoverySteps(); appendLog(bench.dirty ? "已放弃未保存修改，正在启动五阶段自动密钥恢复流程…" : "正在启动五阶段自动密钥恢复流程…"); void startTask(() => StartKeyRecovery({ authorized: true, discardDirty: true }), true); }); readButton.addEventListener("click", () => { let discard = false; if (bench.dirty) { discard = window.confirm("读取卡片会替换当前未保存的工作副本。放弃修改并继续？"); if (!discard) return; } void startTask(() => StartReadCard(discard), true); }); writeChangesButton.addEventListener("click", () => void openPreflight("changes"));
restoreButton.addEventListener("click", () => { restoreWriteUID.checked = false; restoreUIDField.hidden = true; restoreUIDInput.value = bench.uidLength === 4 ? bench.sourceUid || "" : ""; restoreWriteUID.disabled = false; restoreWriteUID.title = "卡型、UID 长度和 sector 0 密钥将在安全预检中检查"; restoreOptionsModal.showModal(); });
restoreWriteUID.addEventListener("change", () => { restoreUIDField.hidden = !restoreWriteUID.checked; if (restoreWriteUID.checked && !restoreUIDInput.value && bench.uidLength === 4) restoreUIDInput.value = bench.sourceUid || ""; });
el<HTMLButtonElement>("#restore-preflight-button").addEventListener("click", (event) => { event.preventDefault(); const writeUid = restoreWriteUID.checked; if (writeUid && !restoreUIDInput.value.trim()) { appendLog("请输入要写入的 4-byte UID", undefined, "error"); return; } restoreOptionsModal.close(); void openPreflight("full", writeUid, restoreUIDInput.value); });
uidWriteButton.addEventListener("click", () => { pendingUIDPreflight = null; uidWriteInput.value = ""; uidWriteConfirm.value = ""; uidWritePreview.replaceChildren(); uidWriteConfirmRow.hidden = true; uidExecuteButton.hidden = true; uidPreflightButton.hidden = false; uidWriteModal.showModal(); });
uidWriteInput.addEventListener("input", () => { pendingUIDPreflight = null; uidWritePreview.replaceChildren(); uidWriteConfirmRow.hidden = true; uidExecuteButton.hidden = true; uidPreflightButton.hidden = false; });
uidPreflightButton.addEventListener("click", async (event) => { event.preventDefault(); uidPreflightButton.disabled = true; uidWritePreview.replaceChildren(text("span", "正在检查卡片与 block 0…")); try { pendingUIDPreflight = (await PreflightUIDWrite(uidWriteInput.value)) as UIDPreflight; uidWritePreview.replaceChildren(); if (!pendingUIDPreflight.valid || !pendingUIDPreflight.preview) { uidWritePreview.append(text("div", pendingUIDPreflight.error || "预检未通过", "preflight-error")); return; } uidWritePreview.append(uidPreviewElement(pendingUIDPreflight.preview)); if (pendingUIDPreflight.warning) uidWritePreview.append(text("div", pendingUIDPreflight.warning, "warning-line")); uidWriteConfirm.value = ""; uidWriteConfirmRow.hidden = false; uidExecuteButton.hidden = false; uidPreflightButton.hidden = true; } catch (error) { uidWritePreview.replaceChildren(text("div", `预检失败：${String(error)}`, "preflight-error")); } finally { uidPreflightButton.disabled = false; } });
uidExecuteButton.addEventListener("click", async (event) => { event.preventDefault(); if (!pendingUIDPreflight?.valid || !pendingUIDPreflight.token) return; uidWriteModal.close(); await startTask(() => StartUIDWrite({ token: pendingUIDPreflight!.token!, confirmation: uidWriteConfirm.value })); pendingUIDPreflight = null; });
cancelButton.addEventListener("click", async () => { if (!activeTask) return; try { await CancelTask(activeTask.id); cancelButton.disabled = true; taskState.textContent = "正在取消"; } catch (error) { appendLog(`取消失败：${String(error)}`, undefined, "error"); } });
rawLogButton.addEventListener("click", () => rawLogModal.showModal());
executeWriteButton.addEventListener("click", async (event) => { event.preventDefault(); if (!pendingPreflight?.valid || !pendingPreflight.token) return; if (pendingPreflight.trailerBlocks.length && !trailerConfirm.checked) { appendLog("必须确认 sector trailer 风险后才能写入", undefined, "error"); return; } if (pendingPreflight.uid && !restoreUIDConfirm.value.trim()) { appendLog("必须再次输入目标 UID 才能写入", undefined, "error"); return; } preflightModal.close(); await startTask(() => StartWrite({ token: pendingPreflight!.token!, confirmTrailers: trailerConfirm.checked, confirmUid: restoreUIDConfirm.value })); pendingPreflight = null; });

EventsOn("nfcx:device-state", (event: DeviceStateEvent) => { const known = devices.findIndex((item) => item.id === event.device.id); if (event.device.connString && known < 0) devices.push(event.device); renderDevices(devices, event.device.id); renderConnection(event.connection); renderCard(event.card); appendLog(`${event.connection.label}${event.connection.detail ? `：${event.connection.detail}` : ""}`, event.time); });
EventsOn("nfcx:card-state", (event: CardEvent) => { cardPrepared = false; renderSectorKeys([]); renderCard(event.type === "appeared" ? event.card : emptyCard); appendLog(event.type === "appeared" ? `检测到卡片 ${event.card.uid}` : `卡片已移除 ${event.card.uid}`, event.time); void GetDashboard().then((dashboard) => renderSectorKeys(dashboard.keys as SectorKey[])); });
EventsOn("nfcx:sector-keys", (entries: SectorKey[]) => renderSectorKeys(entries)); EventsOn("nfcx:key-catalog", (entries: KeyEntry[]) => { catalog = entries; if (keysModal.open) renderCatalog(entries); }); EventsOn("nfcx:workbench", (snapshot: Workbench) => renderWorkbench(snapshot));
EventsOn("nfcx:task", (event: TaskEvent & { engine?: string; stream?: string; log?: string; recoveryError?: string }) => { if (event.log) appendRawLog(event.engine ?? "external", event.stream ?? "output", event.log, event.time); else if (event.message) { appendLog(event.message, event.time, event.type === "failed" || event.recoveryError ? "error" : event.type === "completed" ? "success" : ""); if (event.type === "started" || event.type === "progress") operationHint.textContent = event.message; } if (event.workbench) renderWorkbench(event.workbench); if (event.uid) { const actual = event.uid.actualBlock0 ? `；实际回读 ${event.uid.actualBlock0}` : ""; const backup = event.uid.backupPath ? `；备份 ${event.uid.backupPath}` : ""; appendLog(`UID 写入报告：原 block 0 ${event.uid.oldBlock0}；目标 block 0 ${event.uid.newBlock0}${actual}${backup}`, event.time, event.uid.verified ? "success" : "error"); } updateRecoveryStep(event); if (event.recovery) { pendingRecoveryResult = event.recovery; renderRecoveryResult(event.recovery); } if (event.type === "started" || event.type === "progress") { taskState.textContent = event.step ? `${event.step}/${event.totalSteps || 5} · ${phaseLabel(event.phase).replace(/^\d\/5 · /, "")}` : event.kind === "keyscan" && typeof event.attempted === "number" ? `已尝试 ${event.attempted} · 找到 ${event.found ?? 0}` : phaseLabel(event.phase); taskState.dataset.state = event.phase === "cancelling" ? "cancelling" : "running"; progressBar.classList.toggle("indeterminate", !!event.indeterminate || !event.progress); progressBar.style.width = `${Math.max(2, event.progress || 2)}%`; } else { if (event.kind === "key_recovery") cardPrepared = event.type === "completed" && pendingRecoveryResult?.outcome === "complete" && card.present; if (activeTask?.id === event.taskId) activeTask = null; else terminalTaskIDs.add(event.taskId); taskState.textContent = event.type === "completed" ? t("task.completed") : event.type === "cancelled" ? t("task.cancelled") : t("task.failed"); taskState.dataset.state = event.type; progressBar.classList.remove("indeterminate"); progressBar.style.width = event.type === "completed" ? "100%" : "0%"; updateActions(); if (event.kind === "key_recovery" && pendingRecoveryResult) { renderRecoveryResult(pendingRecoveryResult); if (!recoveryResultModal.open) recoveryResultModal.showModal(); pendingRecoveryResult = null; } } });

async function boot(): Promise<void> {
  refreshLanguage();
  applyTheme(storedTheme());
  try {
    const [dashboard, workspace, storedKeys] = await Promise.all([GetDashboard(), GetWorkbench(), GetKeyCatalog()]);
    recoverButton.title = "Automatically runs common keys, Darkside, Nested, Hardnested (as needed), and read verification";
    aboutVersion.textContent = `v${(await GetDiagnostics() as DiagnosticReport).build.version}`;
    renderDevices(dashboard.devices as Device[], dashboard.selectedDevice);
    renderConnection(dashboard.connection as Connection);
    renderCard(dashboard.card as Card);
    renderSectorKeys(dashboard.keys as SectorKey[]);
    renderWorkbench(workspace as Workbench);
    renderCatalog(storedKeys as KeyEntry[]);
  } catch (error) {
    appendLog(`Initialization failed: ${String(error)}`, undefined, "error");
  }
  try {
    renderDevices((await RefreshDevices()) as Device[]);
  } catch (error) {
    appendLog(`Reader enumeration failed: ${String(error)}`, undefined, "error");
  }
}
void boot();
